export const MENU_DATA =
    {   
        options:
            [
                {
                    index:0,
                    title:'면추가',
                    price:1000,
                    imgUrl:"",
                },
                {
                    index:1,
                    title:'밥 추가',
                    price:1000,
                    imgUrl:"",
                },
                {
                    index:2,
                    title:'소스 추가',
                    price:1000,
                    imgUrl:"",
                },
                {
                    index:3,
                    title:'가라아게 추가',
                    price:4000,
                    imgUrl:"",
                },
                {
                    index:4,
                    title:'감자튀김 추가',
                    price:3000,
                    imgUrl:"",
                },
                {
                    index:5,
                    title:'야채 추가',
                    price:2000,
                    imgUrl:"",
                },
        ],
        categories:[
            {index:0, title: '카테고리0', subCategories:[{index:999, title:"전체"},{index:0, title:"서브0"},{index:1, title:"서브1"},{index:2, title:"서브2"}]},
            {index:1, title: '카테고리1', subCategories:[{index:999, title:"전체"},{index:0, title:"서브0"},{index:1, title:"서브1"},]},
            {index:2, title: '카테고리2', subCategories:[{index:999, title:"전체"},{index:0, title:"서브0"},{index:1, title:"서브1"},{index:2, title:"서브2"},{index:3, title:"서브3"}]},
            {index:3, title: '카테고리3', subCategories:[{index:999, title:"전체"},{index:0, title:"서브0"}]},
            {index:4, title: '카테고리4', subCategories:[{index:999, title:"전체"},{index:0, title:"서브0"},{index:1, title:"서브1"}]},
            {index:5, title: '카테고리5', subCategories:[{index:999, title:"전체"},{index:0, title:"서브0"},{index:1, title:"서브1"},{index:2, title:"서브2"}]},
            {index:6, title: '카테고리6', subCategories:[{index:999, title:"전체"},{index:0, title:"서브0"},{index:1, title:"서브1"},{index:2, title:"서브2"}]},
            {index:7, title: '카테고리7', subCategories:[{index:999, title:"전체"},{index:0, title:"서브0"},]},
        ],
        menus:
        {
            0:{// maincategory
                items:
                {
                    999: // subcategory 전체
                        [
                            {
                                index:0,
                                subCategory:0,
                                title:"낙지 탕탕이",
                                subTitle:'국내산 고기만 사용',
                                detail:'지금까지 이런맛은 없었다.',
                                price:10000,
                                isNew:true,
                                isBest:false,
                                imgUrl:'https://wooriorder.co.kr/order1/upload_file/goods/1689295630-akdsh.jpg',
                                opts:[0,3,1,2]
                            },
                            {
                                index:1,
                                subCategory:0,
                                title:"낙지 탕탕이",
                                subTitle:'국내산 고기만 사용',
                                detail:'지금까지 이런맛은 없었다.',
                                price:10000,
                                isNew:true,
                                isBest:true,
                                imgUrl:'https://wooriorder.co.kr/order1/upload_file/goods/1689295706-sceie.jpg',
                                opts:[0,3,1,2]
                            },
                            {
                                index:2,
                                subCategory:0,
                                title:"낙지 탕탕이",
                                subTitle:'국내산 고기만 사용',
                                detail:'지금까지 이런맛은 없었다.',
                                price:9000,
                                isNew:false,
                                isBest:true,
                                imgUrl:'https://wooriorder.co.kr/order1/upload_file/goods/1690173811-hubsy.gif',
                                opts:[0,3,1,2]
                            },
                        ],
                    0: // subcategory
                        [
                            {
                                index:0,
                                subCategory:0,
                                title:"낙지 탕탕이",
                                subTitle:'국내산 고기만 사용',
                                detail:'지금까지 이런맛은 없었다.',
                                price:10000,
                                isNew:true,
                                isBest:false,
                                imgUrl:'https://wooriorder.co.kr/order1/upload_file/goods/1689295630-akdsh.jpg',
                                opts:[0,3,1,2]
                            },
                        ]
                
                }
            }
        }
    }
    


export const MENU_LIST = [


]


const categoryMenu = [
    {
        itemPk:0,
        itemName:"고고제육면",
        itemPrice:"13,000",
        imgUrl:"https://wooriorder.co.kr/order1/upload_file/goods/1689295671-exdfr.jpg",
        itemAddtion:"국제산/국내산",
        options:[
            {
                pk:1,
                name:"면추가",
                price:1000,
                imgUrl:"https://wooriorder.co.kr/order1/upload_file/goods/1689295671-exdfr.jpg",
            },
            {
                pk:2,
                name:"햄추가",
                price:1100,
                imgUrl:"https://wooriorder.co.kr/order1/upload_file/goods/1689295706-sceie.jpg",
            },
            {
                pk:3,
                name:"당면추가",
                price:1300,
                imgUrl:"https://wooriorder.co.kr/order1/upload_file/goods/1689295706-sceie.jpg",
            },
            {
                pk:4,
                name:"육슈 추가",
                price:1400,
                imgUrl:"https://wooriorder.co.kr/order1/upload_file/goods/1689295671-exdfr.jpg",
            }, 
            {
                pk:5,
                name:"면추가",
                price:1000,
                imgUrl:"https://wooriorder.co.kr/order1/upload_file/goods/1689295706-sceie.jpg",
            },
            {
                pk:6,
                name:"햄추가",
                price:1100,
                imgUrl:"https://wooriorder.co.kr/order1/upload_file/goods/1689295671-exdfr.jpg",
            },
            {
                pk:7,
                name:"당면추가",
                price:1300,
                imgUrl:"https://wooriorder.co.kr/order1/upload_file/goods/1689295706-sceie.jpg",
            },
            {
                pk:8,
                name:"육슈 추가",
                price:1400,
                imgUrl:"https://wooriorder.co.kr/order1/upload_file/goods/1689295671-exdfr.jpg",
            }, 
            {
                pk:9,
                name:"면추가",
                price:1000,
                imgUrl:"https://wooriorder.co.kr/order1/upload_file/goods/1689295706-sceie.jpg",
            },
            {
                pk:10,
                name:"햄추가",
                price:1100,
                imgUrl:"https://wooriorder.co.kr/order1/upload_file/goods/1689295671-exdfr.jpg",
            },
            {
                pk:11,
                name:"당면추가",
                price:1300,
                imgUrl:"https://wooriorder.co.kr/order1/upload_file/goods/1689295630-akdsh.jpg",
            },
            {
                pk:12,
                name:"육슈 추가",
                price:1400,
                imgUrl:"https://wooriorder.co.kr/order1/upload_file/goods/1689295671-exdfr.jpg",
            },
        ],
        recommendMenu:[
            {
                name:"떡볶이",
                price:1000,
                imgUrl:"https://wooriorder.co.kr/order1/upload_file/goods/1689295706-sceie.jpg",
            },
            {
                name:"순대",
                price:1100,
                imgUrl:"https://wooriorder.co.kr/order1/upload_file/goods/1689295630-akdsh.jpg",
            },
            {
                name:"튀김",
                price:1300,
                imgUrl:"https://wooriorder.co.kr/order1/upload_file/goods/1689295706-sceie.jpg",
            },
            {
                name:"김밥",
                price:1400,
                imgUrl:"https://wooriorder.co.kr/order1/upload_file/goods/1689295630-akdsh.jpg",
            },
        ]
    },
    {
        itemPk:1,
        itemName:"존맷탱",
        itemPrice:"11,000",
        imgUrl:"https://wooriorder.co.kr/order1/upload_file/goods/1689295706-sceie.jpg",
        itemAddtion:"국제산/국내산",
        options:[
            {
                name:"면추가",
                price:1000
            },
            {
                name:"햄추가",
                price:1100
            },
            {
                name:"당면추가",
                price:1300
            },
            {
                name:"육슈 추가",
                price:1400
            },
        ],
        recommendMenu:[
            {
                name:"떡볶이",
                price:1000
            },
            {
                name:"순대",
                price:1100
            },
            {
                name:"튀김",
                price:1300
            },
            {
                name:"김밥",
                price:1400
            },
        ]
    },
    {
        itemPk:2,
        itemName:"첵스",
        itemPrice:"6,000",
        imgUrl:"https://wooriorder.co.kr/order1/upload_file/goods/1689295630-akdsh.jpg",
        itemAddtion:"국제산/국내산",
        options:[
            {
                name:"면추가",
                price:1000
            },
            {
                name:"햄추가",
                price:1100
            },
            {
                name:"당면추가",
                price:1300
            },
            {
                name:"육슈 추가",
                price:1400
            },
        ],
        recommendMenu:[
            {
                name:"떡볶이",
                price:1000
            },
            {
                name:"순대",
                price:1100
            },
            {
                name:"튀김",
                price:1300
            },
            {
                name:"김밥",
                price:1400
            },
        ]
    },
    {
        itemPk:3,
        itemName:"코코팝스",
        itemPrice:"9,000",
        imgUrl:"https://wooriorder.co.kr/order1/upload_file/goods/1690173811-hubsy.gif",
        itemAddtion:"국제산/국내산",
        options:[
            {
                name:"면추가",
                price:1000
            },
            {
                name:"햄추가",
                price:1100
            },
            {
                name:"당면추가",
                price:1300
            },
            {
                name:"육슈 추가",
                price:1400
            },
        ],
        recommendMenu:[
            {
                name:"떡볶이",
                price:1000
            },
            {
                name:"순대",
                price:1100
            },
            {
                name:"튀김",
                price:1300
            },
            {
                name:"김밥",
                price:1400
            },
        ]
    },
    {
        itemPk:4,
        itemName:"제육볶음",
        itemPrice:"11,000",
        imgUrl:"https://wooriorder.co.kr/order1/upload_file/goods/1689295671-exdfr.jpg",
        itemAddtion:"국제산/국내산",
        options:[
            {
                name:"면추가",
                price:1000
            },
            {
                name:"햄추가",
                price:1100
            },
            {
                name:"당면추가",
                price:1300
            },
            {
                name:"육슈 추가",
                price:1400
            },
        ],
        recommendMenu:[
            {
                name:"떡볶이",
                price:1000
            },
            {
                name:"순대",
                price:1100
            },
            {
                name:"튀김",
                price:1300
            },
            {
                name:"김밥",
                price:1400
            },
        ]
    },
    {
        itemPk:5,
        itemName:"탕수육",
        itemPrice:"17,000",
        imgUrl:"https://wooriorder.co.kr/order1/upload_file/goods/1689295706-sceie.jpg",
        itemAddtion:"국제산/국내산",
        options:[
            {
                name:"면추가",
                price:1000
            },
            {
                name:"햄추가",
                price:1100
            },
            {
                name:"당면추가",
                price:1300
            },
            {
                name:"육슈 추가",
                price:1400
            },
        ],
        recommendMenu:[
            {
                name:"떡볶이",
                price:1000
            },
            {
                name:"순대",
                price:1100
            },
            {
                name:"튀김",
                price:1300
            },
            {
                name:"김밥",
                price:1400
            },
        ]
    },
    {
        itemPk:6,
        itemName:"파스타",
        itemPrice:"15,000",
        imgUrl:"https://wooriorder.co.kr/order1/upload_file/goods/1690173811-hubsy.gif",
        itemAddtion:"국제산/국내산",
        options:[
            {
                name:"면추가",
                price:1000
            },
            {
                name:"햄추가",
                price:1100
            },
            {
                name:"당면추가",
                price:1300
            },
            {
                name:"육슈 추가",
                price:1400
            },
        ],
        recommendMenu:[
            {
                name:"떡볶이",
                price:1000
            },
            {
                name:"순대",
                price:1100
            },
            {
                name:"튀김",
                price:1300
            },
            {
                name:"김밥",
                price:1400
            },
        ]
    },
    {
        itemPk:7,
        itemName:"피자",
        itemPrice:"23,000",
        imgUrl:"https://wooriorder.co.kr/order1/upload_file/goods/1689295671-exdfr.jpg",
        itemAddtion:"국제산/국내산",
        options:[
            {
                name:"면추가",
                price:1000,
                imgUrl:"https://wooriorder.co.kr/order1/upload_file/goods/1689295671-exdfr.jpg",
            },
            {
                name:"햄추가",
                price:1100,
                imgUrl:"https://wooriorder.co.kr/order1/upload_file/goods/1689295671-exdfr.jpg",
            },
            {
                name:"당면추가",
                price:1300,
                imgUrl:"https://wooriorder.co.kr/order1/upload_file/goods/1689295671-exdfr.jpg",
            },
            {
                name:"육슈 추가",
                price:1400,
                imgUrl:"https://wooriorder.co.kr/order1/upload_file/goods/1689295671-exdfr.jpg",
            },
        ],
        recommendMenu:[
            {
                name:"떡볶이",
                price:1000
            },
            {
                name:"순대",
                price:1100
            },
            {
                name:"튀김",
                price:1300
            },
            {
                name:"김밥",
                price:1400
            },
        ]
    },
];